### ISSUE TITLE
Binary types

### ISSUE THREAD

**Issue by tmpks** [moj-analytical-services/mojap-metadata#24]
- Should the Arrow binary types sit under a binary data type category?
- Should we add a content encoding property for strings, to specify whether they contain binary data encoded in plain text, and which encoding is used?
- Do we need to support binary types at all at this point?
- Other considerations?

**Comment by tmpks** [comment]
@calumabarnett Looks like a binary type category is indeed needed? https://github.com/moj-analytical-services/etl_manager/pull/140

**Comment by calumabarnett** [comment]
@tmpks yes, we've just come across some binary data in Delius
