### ISSUE TITLE
Data type naming conversion discussion

### ISSUE THREAD

**Issue by isichei** [moj-analytical-services/mojap-metadata#26]
# Questions

In this PR #27 I've made the `time` and `timestamp` datatypes more explicit to match Arrow. Some questions / discussion over this PR are split by headings below.

## Should we drop the `date` type category?

Currently this will raise a validation error as dates are categorised as `datetime`. The schema [states](https://github.com/moj-analytical-services/mojap-metadata/blob/faad1b3cfb68912a6954291baf098fd6f5a8b724/mojap_metadata/metadata/specs/table_schema.json#L323) that `date` is a viable `type_category` but I feel like we should group times, timestamps and dates together? As they are quite similar.

```python
Metadata(columns = [{"name": "test", "type": "date64", "type_category": "date"}]) # raises validation error
```

## Should we use square bracket notation instead of round?

Currently to define units in types that require it e.g. `timestamp` we use curly brackets `timestamp(s)` rather than `timestamp[s]`. [The string representation in Arrow](https://arrow.apache.org/docs/python/generated/pyarrow.timestamp.html#pyarrow.timestamp) uses square brackets so I think we should also use square brackets?

**Comment by samtazzyman** [comment]
Definitely happy about putting dates, times, and timestamps together: they are just different ways of describing the same underlying concept.

Don't feel informed enough on the square bracket issue to have a sensible view.

**Comment by nicholsondarius** [comment]
I feel that grouping dates, datetimes and timestamps is logical.

Following the notation used by Arrow for timestamps and their units makes the most sense, so we should probably use square brackets.
Maybe worth noting that Arrow doesn't use square brackets exclusively. `decimal` types for example use round brackets i.e. `decimal(38, 0)`.

**Comment by MrAlecJohnson** [comment]
Is there a risk that storing dates as datetimes can be misleading by implying more precision than is really there? For example, seeing two datetime columns it might seem legitimate to count the hours between them, without realising one was really just a date. 

But definitely see the benefit of dropping date for validation and reducing data wrangling. Could there be a way to have our metadata specify when something is a date, even if storing the information as a datetime?

**Comment by isichei** [comment]
@MrAlecJohnson `dates` won't be dropped there will still be `date` and `timestamp` types. It is just the `type_category` of `date` that will drop. So I think we won't get ambiguity issues (especially if we control old metadata -> new metadata conversion.

@nicholsondarius good point on decimal. Will definitely keep that as is. Will do a bit further digging on time units to see if there is a clear precedence for `[]`

**Comment by isichei** [comment]
Atm I am feeling more inclined to leave in round brackets for everything to be consistent. I think I will merge in the other changes but leave brackets are round. Can readdress this later if we have a strong decision to square brackets.
