### ISSUE TITLE
Converters/Data Types:  What specifically is the 'glue' format and can we use existing code from Arrow to convert data types

### ISSUE THREAD

**Issue by RobinL** [moj-analytical-services/mojap-metadata#4]
- What's it's relation to hive ddl?
- What's it's relation to Spark types
- What's it's relation to Athena types?

If we have a full understanding of ☝️  it might reduce the amount of code we need to write converters - e.g. might help us identify pre-eisting code we can reuse

Related:  is there a difference between data type conversion (i.e. being able to convert the data types from 'agnotistic metadata' to 'pandas types' to 'glue types', and metadata maniupation?  Should these be separate modules?    Are there official versions of these converters 'somewhere upstream' e.g. look in the metadata stored in parquet files (which is different if you write  out from Spark than it is if you write out from pands)  - https://github.com/moj-analytical-services/etl_manager/blob/a99646b37b257d855b1cc1114532bbe1952d7618/etl_manager/meta.py#L1024

Does Apache Arrow have any of these converters in its codebase?

**Comment by RobinL** [comment]
A couple other locations where there's existing data type conversion code:
- pandas codebase (I used it in the archived version of data_linter)
- great expectations

When you start looking at this you quickly realised we do not want to have to write/maintain this code if we can possibly avoid it!

**Comment by RobinL** [comment]
GE codebase dealing with types:

https://github.com/great-expectations/great_expectations/blob/2764099df5edcec98dc3a9260cf927d152d67f63/great_expectations/dataset/pandas_dataset.py#L524

**Comment by RobinL** [comment]
This code shows that something is spark/arrow/python has data type conversion code built in:

https://gist.github.com/RobinL/e9f3598d8d3344562a6a1ecf25f0937a

**Comment by RobinL** [comment]
I'm wondering whether Arrow provides the 'solution' here in that it's intended to provide a 'intermediary' that converts between different libraries and programming languages.  i.e. their codebase will contain all of the gnarly code to handle data type conversions.



For example, using Arrow, you can load a parquet file and convert it into a pandas dataframe, or an R dataframe, do some manipulation and write back out to parquet.

Note: arrow already is performing this role implicitly when you use pandas_df.to_parquet() (it uses pyarrow under the hood to save out)

http://arrow.apache.org/docs/python/pandas.html

**Comment by RobinL** [comment]
![image](https://user-images.githubusercontent.com/2608005/95001271-39696400-05c0-11eb-87a8-242d2883fa27.png)
We want to avoid the 'n choose 2' problem on the left of this slide. 
ref https://youtu.be/fyj4FyH3XdU?t=1977

**Comment by RobinL** [comment]
I think that what we call 'glue' (i.e. glue catalogue/athena) data types are actually hive data types.

Remember that it's possible to define a table in the glue catalogue using hive ddl.

Compare:
https://docs.aws.amazon.com/athena/latest/ug/data-types.html
to
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types#LanguageManualTypes-IntegralTypes(TINYINT,SMALLINT,INT/INTEGER,BIGINT)

**Comment by isichei** [comment]
@RobinL this this is now closed due deciding to use arrow datatypes? In terms of naming Glue or Hive, I think @tmpks thought there might be differences?

**Comment by RobinL** [comment]
@isichei @tmpkns re: glue/hive interested in whether that's 'one is a subset of the other' or 'they sometimes have a different way of referring to the same thing'

**Comment by tmpks** [comment]
>@isichei @tmpkns re: glue/hive interested in whether that's 'one is a subset of the other' or 'they sometimes have a different way of referring to the same thing'

@RobinL I'm not familiar enough with Glue/Hive to say. The uncertainty I expressed to @isichei was regarding the quirkiness of Athena types, the way the set of types you get with Athena DML, `DESCRIBE TABLE` (DDL) statements, selecting from information_schema.columns, and the Glue API are all slightly different.
